# workflow name
name: Generate release-artifacts

# on events
on:
  release:
  push:
  pull_request:

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64, linux/arm64, darwin/arm64, windows/arm64'
            package: '.'
            name: 'sitemapwalk'
            compress: 'false'
            dest: 'dist'
